== Installing the SCAP packages

*SCAP* (Security Content Automation Protocol) is a NIST project that
standardizes the language for describing assessment criteria and
findings. *OpenSCAP*, available in RHEL, is a SCAP based compliance
toolkit that includes policies and tools that allows you to scan and
evaluate host machines.

____
[!NOTE] There are 2 tabs that will be used in this lab - a terminal tab
for running the scanner (indicated by _Terminal_), and a browser tab for
viewing the OpenSCAP report (indicated by _OpenSCAP Report_).
____

Prior to getting started, we will install the package that consists of
the command line interface of the OpenSCAP scanner (_oscap_). OpenSCAP
also has a graphical tool called _SCAP workbench_, but in this lab, we
will only be using the command line interface. We will also install the
SCAP Security guide, which implements security guidance rules and
remediation scripts by respective authorities, namely PCI DSS, STIG,
etc. In this lab, we will scan the system against the PCI DSS profile.

Ensure that apache server, OpenSCAP scanner and definitions are
installed with the command below; it’s safe to run even if the packages
already exist. OpenSCAP is not dependant on apache server, however it is
needed in this lab for the purposes of viewing the HTML report generated
by OpenSCAP.

[source,bash,run]
----
yum install -y httpd openscap-scanner scap-security-guide
----

After installing, all SCAP Security Guide security policies are in the
_/usr/share/xml/scap/ssg/content/_ directory.

[source,bash,run]
----
ls /usr/share/xml/scap/ssg/content
----

If you are interested in more details about the _openscap_ tool check
out -

....
man oscap
....
