== Scan and generate a report

A XCCDF document is a structured collection of security configuration
rules for some set of target system. In this case, it has the
configuration rules that meet the PCI regulation.

To start scanning using OpenSCAP, use the _oscap xccdf eval_ command
with the profile Id, option to fetch remote resources, output XML
results file, and the datastream file.

[source,bash,run]
----
oscap xccdf eval --fetch-remote-resources --profile xccdf_org.ssgproject.content_profile_pci-dss --results /tmp/scan-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml
----

____
[!NOTE] This scan can take a few minutes to complete as it has to
evaluate all the rules, and generate a XML file that has the results.
____

Once the scan completes, you can look at the pass/fail status of each
rule in the output -

The XML results file can be transformed into HTML or plain-text format
for easier readability -

[source,bash,run]
----
oscap xccdf generate report /tmp/scan-xccdf-results.xml > /var/www/html/index.html
----

Now that the HTML report is generated, you can check the **_OpenSCAP
Report_** tab of this lab interface to view the results (You may need to
refresh the OpenSCAP Report tab using the refresh button at the
upper-right of the tab).

In the report, you will notice that several rules have failed. If you
scroll to the bottom of the HTML report, you can find a failed rule.
If you click the failed rule, you can get
more details including the Rule ID, severity and description.
