virtualmachines:
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - git
      - cockpit
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: cockpit
        ports:
          - port: 9090
            protocol: TCP
            targetPort: 9090
            name: cockpit
      - name: rhel-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: http
    routes:
      - name: cockpit
        host: cockpit
        service: cockpit
        targetPort: 9090
        tls: true
        tls_termination: Edge
      - name: rhel-http
        host: rhel
        service: rhel-http
        targetPort: 80
        tls: true
        tls_termination: edge
